### ISSUE TITLE
你好大神，请问有.nii格式转换成.npz格式的数据预处理代码吗？

### ISSUE THREAD

**Issue by minzaa2000** [davidlinhl/med_lib#1]
你好大神，请问有.nii格式转换成.npz格式的数据预处理代码吗？因为我看你做的medSeg套件输入的数据格式是.npz格式，我手头要做的数据格式是.nii，所以想请教您这边有能用的数据预处理代码吗？万分感谢。

**Comment by linhandev** [comment]
可以看看 https://github.com/linhandev/medSeg/blob/main/tool/train/to_slice.py

**Comment by minzaa2000** [comment]
这个npy跟npz是同个东西呀？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linhandev/med_lib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linhandev/med_lib] 你好大神，请问有.nii格式转换成.npz格式的数据预处理代码吗？ (#1)





 
可以看看 https://github.com/linhandev/medSeg/blob/main/tool/train/to_slice.py

**Comment by linhandev** [comment]
没区别，npz是多个数组扔到一个文件里
